// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var onHashChange;
    onHashChange = function(e) {
      var $el, id, s;
      $('body > div').hide();
      id = window.location.hash || '#one';
      $el = $(id);
      $el.show();
      if ($el.is('.iscroll') && !$el.is('.iscrolled')) {
        s = new iScroll($el.get(0), {
          /*
          				handleClick: false	// this doesn't fix it
          */

        });
        return $el.addClass('iscrolled');
      }
    };
    window.addEventListener('hashchange', onHashChange);
    return onHashChange();
  });

}).call(this);
